### PR TITLE
Add Mermaid based eID flow sequence diagrams 

### PR DESCRIPTION
**Pull request by mpanne**

### CODE REVIEW

**Comment by carhartl** [comment]
@mpanne As an idea, not sure how much work it would be to migrate: GitHub markdown since recently support Mermaid out of the box, thus we would get rendering of the diagrams for free, without the need for:

> To display the diagrams use a suitable IDE plugin or copy it to...


https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/
https://mermaid-js.github.io/mermaid/#/sequenceDiagram

**Comment by carhartl** [comment]
I've been using it here for example: https://github.com/digitalservice4germany/mitra-frontend/blob/main/doc/ARCHITECTURE.md

**Comment by mpanne** [comment]
@carhartl That's awesome! I will migrate the diagrams.

**Comment by carhartl** [comment]
I've been using this to preview in VSCode locally: https://marketplace.visualstudio.com/items?itemName=bierner.markdown-mermaid

**Review by pgurusinga — APPROVED** [review]

**Pull request merged**
